// client/src/pages/Landing.svelte
<script>
    import {
      Button,
      Icon
    } from "smelte";
  import { createEventDispatcher } from "svelte";

    const dispatcherModule=createEventDispatcher();
  </script>
  

<main>
	<h5 >Welcome to your new agenda assistant.</h5>
    
	
	<Button on:click={()=>{dispatcherModule("navigate",4)}}>Get Started</Button>
</main>

// client/src/pages/Landing.tsx
import * as React from "react";
import {Text, Button} from "@mantine/core";

const Landing = () => {
    return (
        <>
        
        <Text>Welcome to your new agenda assistant.</Text>
        <a href= "/Authentication">
            <Button>Get Started</Button>
        </a>
        
        </>
        
    )
}

export default Landing;
